# General  
finetune: False
partial_train: null

# Traning 
epochs: 300
batch_size: 32 
lr_backbone: 0.0001
lr_head: 0.0001
weight_decay: 0.01
lr_decay: 0.99

# Model
model_version: class
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.5

# Data
dataset: ntu60_hrnet
data_split: xsub
clip_len: 243
action_classes: 60

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]